### ISSUE TITLE
域名无法解析？

### ISSUE THREAD

**Issue by bobby285271** [zhxsu/index#4]
@SmallOyster

**Comment by SmallOyster** [comment]
对不起。据了解，因工作安排，官网暂未开放。

**Comment by bobby285271** [comment]
https://bobby285271.github.io/zhxsu/
Mirrored.

**Comment by SmallOyster** [comment]
## 现在最主要是域名没有实名认证。

具体怎么操作你们开学再聊吧。

**Comment by bobby285271** [comment]
@SmallOyster 我不是学生会的... 我只是升高二的吃瓜群众罢了...
写策划还不如刷贴吧，搞项目... 不然我的 linux 吧吧务是怎么水出来的...

**Comment by bobby285271** [comment]
![screenshot_2017-10-21-14-04-58-409_com alibaba aliyun](https://user-images.githubusercontent.com/20080233/31848797-74aaabfc-b66b-11e7-9afb-b6866f4c7e3f.png)

itrclub.com 是你注册的？（滑稽） @SmallOyster 
所以 http://zx.itrclub.com/ ... （滑稽）

**Comment by SmallOyster** [comment]
是的，这是作为目前的官网。

但目前官网的源代码已经变了啦。
